// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarvelHeros.Migrations
{
    [DbContext(typeof(MarvelHerosHeroContext))]
    [Migration("20211019121548_new_data_annotations")]
    partial class new_data_annotations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MarvelHeros.Models.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PowerAcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretIdentity")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Hero");
                });
#pragma warning restore 612, 618
        }
    }
}
